### PR TITLE
Disentangle storage concerns from collection and implement subset collections

### LINKED ISSUE #146: Idea: True reference collections
I think podio should support _true_ reference collections. Currently something similar can be achieved by defining a helper data type, a la
```yaml
DataType:
  Members:
    - int member // just some exemplary member

DataTypeReference:
  Members: {}
  OneToOneRelations:
    - DataType referenced // reference to the actual datatype
```

However, this is slightly awkward in its usage, as there is always an additional indirection to get to the actual information

```cpp
auto& referenceCollection = eventStore.get<DataTypeReferenceCollection>("refCollection");
auto ref  = referenceCollection[0];
auto data = ref.getReferenced();
int i = data.getMember();
```

Also setting this is slightly cumbersome
```cpp
auto& dataCollection = eventStore.create<DataTypeCollection>("dataCollection");
auto& referenceCollection = eventStore.create<DataTypeReferenceCollection>("refCollection");

auto data = dataCollection.create();
auto ref = referenceCollection.create();
ref.setReferenced(data);
```

Ideally, reference collections behave the same as normal collections when they are `const`, i.e. reference collections do not allow to alter the objects they reference in any way, but can be used for _read only_ access to them. So something along the lines:

```yaml
DataType:
  Members:
    - int member // just some exemplary member
```

for which podio would generate a `DataTypeCollection` and a `DataTypeRefCollection` (naming is just a proposal here, also to distinguish it from the above example more clearly). So that in the end the usage would look something like this

```cpp
// when writing
auto& dataCollection = eventStore.create<DataTypeCollection>("dataCollection");
auto& referenceCollection = eventStore.create<DataTypeRefCollection>("refCollection");

auto data  = dataCollection.create();
referenceCollection.push_back(data);
// changes to data should still be properly propagated to the reference object


// when reading
auto& referenceCollection  = eventStore.get<DataTypeRefCollection>("refCollection");
auto data = referenceCollection[0];
int i = data.getMember();
```

I am not yet completely sure about the internals, but I think something like this should be possible. From a persistency point of view it should in principle work like any other `OneToOneRelation` and storing a `vector<ObjectID>` should be enough to rebuild the reference collection after reading it in. One of the major changes that would be necessary is probably to change the layout of the `Obj` classes from storing a `Data` object to only having a pointer to a `Data` object. I have already briefly mentioned this earlier in https://github.com/AIDASoft/podio/pull/129#issue-474854578 . However, since then I haven't really checked what would actually be necessary to make that change work.

This is at the moment just an idea and an early draft of an implementation, so any input is very welcome.

### LINKED ISSUE #166: Variadic create function for Collection breaks with Objects that have relations
The variadic `create` function of the Collections:
https://github.com/AIDASoft/podio/blob/cf3d239cbc4932e2b1d7ee42bcbef55ee869b3c1/python/templates/Collection.h.jinja2#L164-L170

is broken for all collections that store objects which have relations. E.g. the following will break
```cpp
auto store = podio::EventStore();
auto& clusters = store.create<ExampleClusterCollection>("clusters");
auto variadic_cluster = clusters.create(3.14f);
auto normal_cluster = clusters.create();
normal_cluster.energy(42);

// this will break and crash the program
variadic_cluster.addClusters(normal_cluster);
```

The reason is that the constructor for `Obj` that starts from a `Data` struct does not initialize the relation pointers. Especially for OneToManyRelations this is a problem, because it expects a valid `std::vector` pointer to be present in the `Obj`.

The fix would not be too hard, but the other question is whether we want to support this variadic template `create` method in the first place, since it relies on the order of the members `Data` and together with implicit conversions, this is a pretty dangerous constructor that could lead to very subtle bugs.

### PR DESCRIPTION
**Pull request by tmadlener**
BEGINRELEASENOTES
- Introduce a `podio::CollectionBuffers` class that contains everything that is necessary for I/O of a given collection. **This is a breaking change in the collection interface** 
- Introduce  and generate a `CollectionData` class for each datatype that only manages the storage of a given collection.
  - Exposes only the `Obj` entries of each collection as well as the necessary functionality to add a new object (and its relations) to the collection.
- Implement "subset" collections that behave exactly the same as normal collections apart from an additional function call when creating them.

ENDRELEASENOTES

The `CollectionBuffers` helpers class makes the interaction between the readers/writers and the collections a bit clearer as it now happens in one function call instead of the three it took previously to connect all the buffers to the I/O system. This is a breaking change in the collection interface, but it is quite easy to fix on the calling side, where we now have
```cpp
const auto collBuffers = coll->getBuffers();

// the data buffer (address)
void* rawbuffer = collBuffers.data; // previously was coll->getBufferAddress();
const auto* buffer = collBuffers.dataAsVector<Data>(); // get a vector<Data>* if we know the datatype
// relations and vector members
const auto* refCollections = collBuffers.references; // previously was coll->referenceCollections();
const auto* vecMembers = collBuffers.vectorMembers; // previously was coll->vectorMembers();
```

The `CollectionData` classes manage everything that concerns the storage of a collection. They only expose the `entries` member to give a collection access to the entries of a collection. The `prepareAfterRead`, `prepareBeforeWrite`, `setReferences`  and `getBuffers` functions of the `Collection` are now essentially only passing through to the `CollectionData` which does all the heavy lifting. This now make the storage concerns separated enough from the collection interface that subset (aka "true reference") collections can be implemented without having to introduce a separate `RefCollection` class. The interface is the following:

```cpp
// FILLING
auto& recos = store.create<edm4hep::ReconstructedParticleCollection>("recos");
// fill

auto& muons = store.create<edm4hep::ReconstructedParticleCollection>("muons");
muons.setSubsetCollection(); // declare this as a subset collection
// Here I can only store objects already tracked by another collection
muons.push_back(recos[0]);

// READING
auto& muons = store.get<edm4hep::ReconstructedParticleCollection>("muons");
for (auto muon : muons) { /* use as ConstReconstructedParticle */ }
```

So when creating a subset collection one has to declare it as such with a separate function call, but when reading they behave as if they were a normal collection. The function call to declare a collection to be a subset collection could potentially be put into the `EventStore::create` call somehow if it is deemed too cumbersome.

Supersedes #177
Fixes #146, Fixes #166

- [x] Subset collections
- [x] Test with edm4hep
- [x] Clean up templates (and generated code)
- [x] Clean up commits

### CODE REVIEW

**Comment by tmadlener** [comment]
This is ready for review now. It has become quite big, because it also incorporates reference collections already. That could be moved to a separate PR if necessary. However, since this splitting of concerns is also at least partially driven by the reference collections, I thought it is good to have these two together.

**Comment by andresailer** [comment]
There is already a function called `referenceCollections`
https://github.com/AIDASoft/podio/blob/02d613f69dde4f8c571e0084e6036ea89ac048db/python/templates/Collection.h.jinja2#L87
Which is not related to the reference collection discussed here, is it?

**Comment by tmadlener** [comment]
> Which is not related to the reference collection discussed here, is it?

That is correct. I think the naming is a bit confusing here as *reference* is used slightly differently in different contexts.

`referenceCollections` returns the `ObjectID`s for all `OneToManyRelations` and `OneToOneRelations` that are persisted for a given collection. `podio::CollRefCollection` is just a typedef:
https://github.com/AIDASoft/podio/blob/eb298b1c0e935c8ba18a8c5726328846ccfbaa89/include/podio/CollectionBase.h#L16

On the other hand the *reference collections* this PR is about, are collections that hold references to objects that are owned by a different collection.

Maybe this can be addressed with a more consistent naming? E.g. by renaming `CollectionBuffers::references` to `CollectionBuffers::relations` (`referenceCollections` will be gone in any case after this PR).

**Comment by tmadlener** [comment]
As discussed during the last meeting, I have renamed the reference collections to subset collections, following the same naming as in LCIO to try and reduce the confusion.

**Comment by hegner** [comment]
Hi @tmadlener - what is the current status of this? I see the item of code cleanup open.

**Comment by tmadlener** [comment]
From a quick look, there still are some comments in the templates that can be removed. I will have another look at this to see if there is more. Other than that, basically done, unless there is additional feedback.

**Comment by tmadlener** [comment]
I have replaced the last spurious occurrences of "reference collections" with "subset collections" and also removed commented code from the templates.

File: include/podio/CollectionBase.h [hunk 1]
```diff
@@ -57,11 +51,11 @@ namespace podio {
     /// clear the collection and all internal states
     virtual void clear() = 0 ;
 
-    /// return the buffers containing the object-relation information
-    virtual CollRefCollection* referenceCollections() = 0;
+    /// check if this collection is a reference collection
```
Comment (hegner) [inline include/podio/CollectionBase.h:54]: "reference collection"

File: include/podio/CollectionBase.h [hunk 2]
```diff
@@ -57,11 +51,11 @@ namespace podio {
...
+    virtual bool isSubsetCollection() const = 0;
 
-    /// return pointers to vector members
-    virtual VectorMembersInfo* vectorMembers() = 0;
+    /// declare this collection to be a reference collection
```
Comment (hegner) [inline include/podio/CollectionBase.h:57]: "reference collection"

File: include/podio/ROOTReader.h [hunk 3]
```diff
@@ -80,6 +80,8 @@ class ROOTReader : public IReader {
 
 
   private:
+    void createCollectionBranches(const std::vector<std::tuple<int, std::string, bool>>& collInfo);
+
     std::pair<TTree*, unsigned> getLocalTreeAndEntry(const std::string& treename);
     // Information about the data vector as wall as the collection class type
```
Comment (hegner) [inline include/podio/ROOTReader.h:86]: ...as well...

File: python/templates/CollectionData.cc.jinja2 [hunk 4]
```diff
@@ -0,0 +1,211 @@
...
+{{ class_type }}::{{ class_type }}() :
+{%- for relation in OneToManyRelations + OneToOneRelations %}
+  m_rel_{{ relation.name }}(new std::vector<{{ relation.namespace }}::Const{{ relation.bare_type }}>()),
+{%- endfor %}
+{%- for member in VectorMembers %}
+  m_vec_{{ member.name }}(new std::vector<{{ member.full_type }}>()),
+{%- endfor -%}
+  m_data(new {{ class.bare_type }}DataContainer()) {
+{% for relation in OneToManyRelations + OneToOneRelations %}
+  m_refCollections.push_back(new std::vector<podio::ObjectID>());
```
Comment (hegner) [inline python/templates/CollectionData.cc.jinja2:24]: why not emplace_back?

File: python/templates/CollectionData.cc.jinja2 [hunk 5]
```diff
@@ -0,0 +1,211 @@
...
+    isRefColl ? nullptr : (void*)&m_data,
+    &m_refCollections, // only need to store the ObjectIDs of the referenced objects
+    &m_vecmem_info
+  };
+}
+
+void {{ class_type }}::prepareForWrite(bool isRefColl) {
+  for (auto& pointer : m_refCollections) { pointer->clear(); }
+
+  // If this is a reference collection use the relation storing mechanism to
```
Comment (hegner) [inline python/templates/CollectionData.cc.jinja2:93]: reference collection...

**Review by hegner — CHANGES_REQUESTED** [review]
Thanks. Nice work and cleanup done alongside.

There are two things that we should add to the tests 
(unless I overlooked it):
1) having a subset collection in a file with the original object missing.
2) check the subset collection for adding objects from two different collections.

File: python/templates/CollectionData.cc.jinja2 (hunk 4 above)
Comment (hegner) [reply python/templates/CollectionData.cc.jinja2:24]: well. I think I can agree with you. thanks.

**Comment by hegner** [comment]
> > 1. having a subset collection in a file with the original object missing.
> 
> This will currently result in a `nullptr` access and a pretty ugly crash, I think. How should we handle this, ideally? Resp. what is the latest point that we can get away with?

It depends a bit on whether we want to really only have subsets of collections, Or whether we dare to have references into multiple collections (better not!). If we are only talking about subsets, If we have real subsets, a consistency check on whether the previous collection is there would suffice. We can play with the reader and some metadata about collection dependencies there.

In general, I have my issues with the subset collections, when it comes to later dropping of collections... but that would be a different discussion.

**Comment by tmadlener** [comment]
From a technical point of view "subset" collections can store elements from many different collections. The only requirement that is really there is that all objects that are put into a subset collection are already stored in another collection, as they need to have a valid ObjectID. (This is also the reason why I called them reference collections in the beginning). From there storage basically works equivalent to `OneToOneRelations`.

Looking at the handling of relations in general, the current implementation seems to break quite easily if collections where related objects live are are no longer present. One possibility for subset collections could be to have a way of storing a copy of the data of the original objects on demand. However, that would break some of the assumptions when a collection stored this way is read in again (most importantly the ObjectIDs of the stored elements would have changed).

File: tests/write_test.h [hunk 6]
```diff
@@ -166,6 +171,31 @@ void write(podio::EventStore& store, WriterT& writer) {
...
+      if (p.id() % 2) {
+        mcpsRefs.push_back(p);
+      }
+    }
+    // ----------------- add the "even" counterparts from a different collection
+    for (auto p : moreMCs) {
+      if (p.id() % 2 == 0) {
+        mcpsRefs.push_back(p);
+      }
+    }
```
Comment (tmadlener) [inline tests/write_test.h:192]: > 2. check the subset collection for adding objects from two different collections.

I added this test here that uses original objects from two different collections, and so also shows that the subset collections do not technically have to be subsets of one collection.

Comment (hegner) [reply tests/write_test.h:192]: thanks

**Comment by hegner** [comment]
There was a notion of marking ObjectIDs as invalid. we should come back to that.

Thanks for clarifying the subset part. In that case, we have to couple the data with some metadata to allow a check-on-write of completeness (are all required collections there?) Otherwise the reading will have to do it, which is much slower.

**Review by hegner — APPROVED** [review]
